name: test
on: [push]
jobs:
  test:
    name: Hello World
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: "8.8.3"
          enable-stack: true
          stack-version: "2.5.1"
      - run: stack test
